name: Submit Dependencies
on:
  push:
    branches:
      - main

jobs:
  submit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Submit Gradle dependencies
        uses: mikepenz/gradle-dependency-submission@v0.8.4

