name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Submit Gradle Dependencies
        uses: mikepenz/gradle-dependency-submission@{latest}
